### ISSUE TITLE
Multiple Inverter Name Support

### ISSUE THREAD

**Issue by matthewjporter** [squishykid/solax#1]
First off, Great work on this. I know there is a few people using SolaX inverts so much appreciated

Question, Are you able to add a "name" to the platform allowing for multiple sensors to be added

I have two inverters and homeassistant by default is adding the second inverter as "_2" on the end but is hard to distinguise between the two

Not sure if it works this way but would the following be how it works?
sensor:
  - platform: solax
    ip_address: IP_ADDRESS
    name: inverter1

  - platform: solax
    ip_address: IP_ADDRESS
    name: inverter2

This would produce the sensors in the following format

sensor.inverter1_battery_capacity
and
sensor.inverter2_battery_capacity

**Comment by squishykid** [comment]
Yep, this is definitely possible. You should open this issue on the home-assistant repo though, as the changes to support this will be implemented there.

Thank you for the feedback :)

**Comment by matthewjporter** [comment]
Will do mate

**Comment by squishykid** [comment]
Follow the PR here:

https://github.com/home-assistant/home-assistant/pull/24707
