### ISSUE TITLE
Growatt sph3600

### ISSUE THREAD

**Issue by fontexD** [squishykid/solax#113]
Grid power seems to be wrong i got a esp on my Meter directly connected, currently my solax says 0W where it should say quite higher number

https://ibb.co/k66B2Bw

**Comment by fontexD** [comment]
thse also seems to be wrong 
https://ibb.co/mhkCHkw

**Comment by squishykid** [comment]
Hello, yes, this doesn't seem correct

Please supply the API response from the inverter and the curl command used to get the data. See here for an example: https://github.com/squishykid/solax/issues/75

Or here for some more examples: https://github.com/squishykid/solax/wiki/Adding-Support-for-Your-Inverter

Once you supply the API response and the mapping, we can fix your inverter.

**Comment by squishykid** [comment]
closing for now, please raise a PR with your data
