### ISSUE TITLE
solax inverter official page

### ISSUE THREAD

**Issue by sommo** [squishykid/solax#19]
Sorry for using this github page, but official support/forum seems to not exist (or lack).
Have you some problem with your inverter data display via official app, seems having trouble since 2-3 weeks, the data is not display correctly like solax's server collect only a few moment of data.
Just for asking to know if its only my problem or not.
Cheers to all

**Comment by sommo** [comment]
None of you that have Solax inverter use their app?
This is what I get:
![994DA999-A5EB-4976-ADA3-F17525C15924](https://user-images.githubusercontent.com/22022996/79168329-ea4d2e00-7de9-11ea-857b-8e0656866eee.png)

**Comment by sommo** [comment]
None of you that have Solax inverter use their app?
This is what I get:
![6B87BEEB-1E17-4696-B217-36345564B009](https://user-images.githubusercontent.com/22022996/79168433-2b454280-7dea-11ea-9c59-3319a3cdd64a.jpeg)

**Comment by squishykid** [comment]
Hey, apologies, but I don't know about the app. Maybe you could email them? This github project is only trying to make a python library so you can download data for yourself without the app.
