### ISSUE TITLE
Add support for X3-Hybrid (3 phase units)

### ISSUE THREAD

**Issue by bbnsn** [squishykid/solax#20]

**Comment by bbnsn** [comment]
Hi @squishykid I'm actually a Hubitat user (we share the same tech interests: solax, synology etc) and i'm keen to emulate your success with my solax inverter. Hubitat is a Groovy-based platform. do you know how feasible it is to convert your HA/python to something that will work with Hubitat?

**Comment by squishykid** [comment]
I haven't had a chance to have a proper look at the hubitat docs, but if you can make a plugin that is able to make HTTP requests and parse the response, you could do the same as this library.

**Comment by bbnsn** [comment]
thanks @squishykid i'm a beginner but i guess i'll try to figure it out, i do like my solax inverter and would love to use the data it provides more intelligently
