### ISSUE TITLE
Fix Release pipeline to use version from tag

### ISSUE THREAD

**Issue by squishykid** [squishykid/solax#34]

**Comment by BoBiene** [comment]
@squishykid the 0.2.7 is missing at https://pypi.org/project/solax/#history is this issue the reason?

**Comment by squishykid** [comment]
Yep. Sorry about the delay :( I can do a manual release for now

**Comment by BoBiene** [comment]
That would help 👍

**Comment by squishykid** [comment]
Whoops, seems like it was working all along. The issue was that I had already created the github release.

@BoBiene 0.2.7 is now on PyPi

**Comment by squishykid** [comment]
also, it's being updated in home-assistant: https://github.com/home-assistant/core/pull/54205
