### ISSUE TITLE
Support for new Home Assistant Energy sensors

### ISSUE THREAD

**Issue by matthewjporter** [squishykid/solax#35]
Hi

Have you played with the new Energy component in Home Assistant yet?

Looking at the requirements, the Solax sensors are not "storing" or created in the right way to add into the Energy dashboard

Just wondering if you have added them in yet? I know its early days but just wondering

Cheers

**Comment by squishykid** [comment]
This might be a great weekend project. Thanks for the tip!

**Comment by squishykid** [comment]
This has been raised here: https://github.com/home-assistant/core/issues/54056

So i will close this issue for now, we can track it in the home-assistant project, where the changes will need to be made
