### ISSUE TITLE
Update Home Assistant Plugin

### ISSUE THREAD

**Issue by KuzonCode** [squishykid/solax#44]
Hi Mate,

I don't think this is against the right repository but can't work out how to raise it against the home assistant one.

I am trying to set up the Energy function in HA, and it is saying I can't add it because it's not a statistic. 

It's said to raise a ticket with reference to https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

The recommendation is here https://www.home-assistant.io/more-info/statistics/

**Comment by squishykid** [comment]
G'day champion, this has already been added here: https://github.com/home-assistant/core/pull/54654

Patience, it will be in the next release ;)

**Comment by KuzonCode** [comment]
Absolute Legend! Thanks Mate

On Saturday, 28 August 2021, Robin Wohlers-Reichel ***@***.***>
wrote:
> G'day champion, this has already been added here:
home-assistant/core#54654
>
> Patience, it will be in the next release ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci3.googleusercontent.com/proxy/2TVkSqfBVwM8os9OiL9Xh2XwR8YkhPLjbFeXW7RjUOsfm36FgobBLYeBVblk-2UT1Hqvhi3gF49R_N-FZPwaHIYblHn-ncmfBOJ3-QSom2ExkdQma2cdngMRNMjlU1Rm0CyqbawiXxcNfAeSrtUvdbX06nMS4SQzcD0CWzmrQVFx82iO4SJs7DqLuPHHBsVXCBAYeRbz0tmdYE9bcVTntBxdYg_3sczyUOAMQC8H3g=s0-d-e1-ft#https://github.com/notifications/beacon/AB7GTIZZMLGTGIXUEVOPUNTT7CFRRA5CNFSM5C4VR5JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGYMK2IA.gif>

**Comment by DerDet** [comment]
Hi,
I'm at a loss here. I want to use this wonderful Plugin for Homassistant. 
But the Solax Integration in HA is not the same as shown in the project.
I use HA (HA-OS) and I'm not able to install via Python script.
so, is there anybody out there, who can tell me, if I can use it into HA?

Thanks a lot 
Best
Der Det
