### ISSUE TITLE
how can use it

### ISSUE THREAD

**Issue by sommo** [squishykid/solax#8]
Hi,
i install all the package, create a file called solax:

import solax
import asyncio

r = solax.RealTimeAPI('10.0.0.1')

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
data = loop.run_until_complete(r.get_data())

with the right ip of my inverter.

then i execute python3 solax, but how to output the data?
Thank you

**Comment by squishykid** [comment]
`print(data)`
